### PR TITLE
Education Tests Done

### PR DESCRIPTION
**Pull request by bonganiklaas**

### CODE REVIEW

**Comment by boniface** [comment]
conflicts in this

**Comment by vuyokazi8110** [comment]
Guys I am struggling to resolve those conflicts as  do not see anything wrong from the code. Please help.

Kind regards

**Comment by wandilediba** [comment]
Payroll was not assigned to you....

**Comment by vuyokazi8110** [comment]
The conflicts I am talking about are on Education Test... #171 which was assigned to me.

**Comment by wandilediba** [comment]
your pull request have education tests and some tables from payroll

I will suggest you separate tests from other stuff and make another pull
request.

**Comment by vuyokazi8110** [comment]
Conflicts does not come from the code, it comes from the Repo, the best option is to create one pull request for one test at the time and pull another test for the second test, and so on, this will help you to identify which class course a conflict with the master. hope this help....

**Comment by vuyokazi8110** [comment]
Conflicts does not come from the code, it comes from the Repo, the best option is to create one pull request for one test at the time and pull another test for the second test, and so on, this will help you to identify which class course a conflict with the master. hope this help.... from Bongani Klaas

**Comment by bonganiklaas** [comment]
Conflicts does not come from the code, it comes from the Repo, the best
option is to create one pull request for one test at the time and pull
another test for the second test, and so on, this will help you to identify
which class course a conflict with the master. hope this help.... from
Bongani Klaas

**Pull request closed without merging**
